# Generated by Django 4.2.16 on 2026-06-03 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agricultor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('zona', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=20)),
                ('imagen', models.ImageField(upload_to='agricultores/')),
            ],
        ),
        migrations.CreateModel(
            name='ProductoAgricola',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unidad', models.CharField(max_length=20)),
                ('imagen', models.ImageField(upload_to='productos/')),
                ('agricultor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agricultura.agricultor')),
            ],
        ),
    ]
